spring:
  rabbitmq:
    host: 192.168.200.234
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://192.168.200.234:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
zuul:
  #全部服务忽略敏感头(全部服务都可以传递cookie)
  sensitive-headers: 
  routes:
  # /myProduct/product/list -> /product/product/list
    product:
      path: /product/**
      serviceId: product
      sensitiveHeaders:  #显示敏感头信息（cookie，配置空即可）
    order:
      path: /order/**
      serviceId: order
      sensitiveHeaders:  #显示敏感头信息（cookie，配置空即可）
    user:
      path: /user/**
      serviceId: user
      sensitiveHeaders:  #显示敏感头信息（cookie，配置空即可）
  #简洁写法
#    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder 
#暴露配置，
#通过：http://localhost:9000/actuator/routes可以查看所有匹配的路由
#低版本：http://localhost:9000/applicatio/routes查看
management:
  endpoints:
    web:
      exposure:
        include: "*"  
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000

