spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhousheng
    url: jdbc:mysql://192.168.56.100:3306/springCloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.56.100
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.56.100
    port: 6379
env:
  test13
girl:
  name: mo
  age: 18
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
# 暴露actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
