spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhousheng
    url: jdbc:mysql://192.168.56.100:3306/springCloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.56.100
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
