spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhousheng
    url: jdbc:mysql://192.168.200.138:3306/springCloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.200.138
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.200.138
    port: 6379
  jpa:
    show-sql: true
  zipkin:
    base-url: http://192.168.200.138:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
girl: 66
management:
  endpoints:
    web:
      exposure:
        include: "*" 

