spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhousheng
    url: jdbc:mysql://192.168.56.100:3306/springCloud_sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.56.100
    port: 6379
