spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhousheng
    url: jdbc:mysql://192.168.200.234:3306/springCloud_sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.200.234
    port: 6379
  jpa:
    show-sql: true
    open-in-view: false
